# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('license', models.CharField(max_length=200, verbose_name='license')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentName', models.TextField(verbose_name='current_name')),
                ('currentPosition', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='current_position')),
                ('datasetSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.DatasetSeries')),
            ],
        ),
    ]
