# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('attribType', models.CharField(max_length=200, verbose_name='attrib_type')),
                ('datasetSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.DatasetSeries')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.CharField(default='', max_length=200, verbose_name='name')),
                ('dataJson', models.TextField(verbose_name='data_json')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('datasetSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.DatasetSeries')),
            ],
        ),
        migrations.CreateModel(
            name='RecordTextAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='fieldName')),
                ('data', models.TextField(verbose_name='data')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('attrib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.AttributeType')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='externalId',
            field=models.CharField(default='', max_length=200, verbose_name='license'),
        ),
        migrations.AddField(
            model_name='recordtextattribute',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record'),
        ),
        migrations.AddField(
            model_name='recordtextattribute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetrecord',
            name='datasetSnapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.DatasetSnapshot'),
        ),
    ]
