# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20161229_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtextattribute',
            name='name',
        ),
    ]
